# Generated by Django 4.1.3 on 2022-11-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="nicho",
            field=models.CharField(
                choices=[
                    ("M", "Marketing"),
                    ("N", "Nutrição"),
                    ("D", "Designer"),
                    ("T", "Tecnologia"),
                ],
                default=1,
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
